package nutrisoft.telas;

import javax.swing.JOptionPane;

/**
 *
 * @author Wendell Marcos
 */
public class Loading extends javax.swing.JFrame {

    /**
     * Creates new form Loading
     */
    public Loading() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        progresso = new javax.swing.JProgressBar();
        porcentagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setLocationByPlatform(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setToolTipText("");
        jPanel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nutrisoft/telas/imagens/769.gif"))); // NOI18N
        jPanel1.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        progresso.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        progresso.setDoubleBuffered(true);
        progresso.setStringPainted(true);
        jPanel1.add(progresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 210, 23));

        porcentagem.setText("99");
        jPanel1.add(porcentagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 280, 0, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void carregar() {

        Loading loading = new Loading();

        loading.setVisible(true);

        for (int i = 0; i < 100; i ++) {
            try {
                Thread.sleep(20);
            } catch (InterruptedException e) {
                JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
            }

            loading.porcentagem.setText(Integer.toString(i) + "%");
            progresso.setValue(i);

            if (i == 100) {
                
                loading.dispose();
                

                TelaInicial telaInicial = new TelaInicial();
                telaInicial.setVisible(true);
                
            }

        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel porcentagem;
    public static javax.swing.JProgressBar progresso;
    // End of variables declaration//GEN-END:variables
}
