/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nutrisoft.telas;

import javax.swing.JOptionPane;

/**
 *
 * @author Wendell Marcos
 */
public class TelaIMC extends javax.swing.JFrame {

    /**
     * Creates new form TelaIMC
     */
    public TelaIMC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnImcVoltar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnCalcular = new javax.swing.JButton();
        campoAltura = new javax.swing.JTextField();
        campoPeso = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        fieldResposta = new javax.swing.JTextArea();
        respostaImc = new javax.swing.JLabel();
        btnImcSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NUTRI SOFT");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(470, 450));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnImcVoltar.setText("Voltar");
        btnImcVoltar.setToolTipText("Aperte para voltar");
        btnImcVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImcVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnImcVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, -1, -1));

        btnCalcular.setText("Calcular");
        btnCalcular.setToolTipText("Aperte para calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        btnCalcular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCalcularKeyPressed(evt);
            }
        });

        campoAltura.setToolTipText("Insira a Altura");
        campoAltura.setNextFocusableComponent(campoPeso);
        campoAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoAlturaActionPerformed(evt);
            }
        });

        campoPeso.setToolTipText("Insira o Peso");
        campoPeso.setNextFocusableComponent(btnCalcular);
        campoPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPesoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Altura (m):");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Peso (kg):");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(campoPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(campoAltura)))
                .addGap(127, 127, 127))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCalcular)
                .addGap(155, 155, 155))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCalcular)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 74, -1, -1));

        jLabel3.setText("Resultado:");

        jLabel4.setText("Interpretação:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 130, 100));

        fieldResposta.setColumns(20);
        fieldResposta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fieldResposta.setRows(5);
        jScrollPane2.setViewportView(fieldResposta);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 290, 40));

        respostaImc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        respostaImc.setText(" ");
        getContentPane().add(respostaImc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 100, 30));

        btnImcSair.setText("Sair");
        btnImcSair.setToolTipText("Aperte para voltar");
        btnImcSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImcSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnImcSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnImcVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImcVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnImcVoltarActionPerformed

    private void campoPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPesoActionPerformed
        String mensagemErro = "Verifique se escreveu corretamente ";
        try {
            if (campoPeso.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "O campo Peso precisa ser preenchido: ");
            } else {
                double peso = Double.parseDouble(campoPeso.getText().replace(",", "."));
            }
        } catch (NumberFormatException error) {
            JOptionPane.showMessageDialog(null, mensagemErro + error.getMessage());
        }
    }//GEN-LAST:event_campoPesoActionPerformed

    private void campoAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoAlturaActionPerformed
        String mensagemErro = "Verifique se preencheu corretamente ";
        try {
            if (campoAltura.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "O campo Altra precisa ser preenchido: ");
            } else {
                double altura = Double.parseDouble(campoAltura.getText().replace(",", "."));
            }
        } catch (NumberFormatException error) {
            JOptionPane.showMessageDialog(null, mensagemErro + error.getMessage());
        }
    }//GEN-LAST:event_campoAlturaActionPerformed


    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed

        double imc;
        String mensagem;
        String mensagemErro = "O campo Altura precisa ser preenchido ou o campo Peso ";

        

        try {

            double altura = Double.parseDouble(campoAltura.getText().replace(",", "."));
            double peso = Double.parseDouble(campoPeso.getText().replace(",", "."));
            imc = peso / (altura * altura);
            

            if (campoAltura.getText().isEmpty() || campoPeso.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, mensagemErro);
            } else {
                if (imc < 18.5) {
                    mensagem = String.format(" Você está muito magro.\n Precisa de uma dieta para engordar \n Seu IMC é:  %.2f ", imc);
                } else if (imc < 24.9) {
                    mensagem = String.format("Você está com peso ideal. \nNão precisa de dieta\n Seu IMC é: %.2f", imc);
                } else if (imc < 29.9) {
                    mensagem = String.format("Você está com sobrepeso. \nPrecisa de uma dieta para emagrecer\n Seu IMC é: %.2f", imc);
                } else if (imc < 30) {
                    mensagem = String.format("Você está com obesidade. \nPrecisa de uma dieta, exercícios e uma mudança de vida \nSeu IMC é:  %.2f", imc);
                } else {
                    mensagem = String.format("Você está com obesidade grave. \nPrecisa procurar um médico\nSeu IMC é: %.2f", imc);
                }
                fieldResposta.setText(mensagem);
                String textImc = String.format("%.2f", imc);
                respostaImc.setText(textImc);
            }
        } catch (NumberFormatException error) {
            JOptionPane.showMessageDialog(null, mensagemErro + error.getMessage());
            return;
        }

        limparCampos();


    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnCalcularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCalcularKeyPressed

    }//GEN-LAST:event_btnCalcularKeyPressed

    private void btnImcSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImcSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnImcSairActionPerformed

    public void limparCampos() {
        campoPeso.setText("");
        campoAltura.setText("");

    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnImcSair;
    private javax.swing.JButton btnImcVoltar;
    private javax.swing.JTextField campoAltura;
    private javax.swing.JTextField campoPeso;
    private javax.swing.JTextArea fieldResposta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel respostaImc;
    // End of variables declaration//GEN-END:variables
}
