/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nutrisoft.telas;

import javax.swing.JOptionPane;

/**
 *
 * @author Wendell Marcos
 */
public class TelaGastoCalorico extends javax.swing.JFrame {

   

    /**
     * Creates new form TelaGastoCalorico
     */
    public TelaGastoCalorico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoRadio = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnCalcularGasto = new javax.swing.JButton();
        radioMulherTelaGasto = new javax.swing.JRadioButton();
        radioHomemTelaGasto = new javax.swing.JRadioButton();
        campoPesoTelaGasto = new javax.swing.JTextField();
        campoAlturaTelaGasto = new javax.swing.JTextField();
        campoIdadeTelaGasto = new javax.swing.JTextField();
        txtPeso = new javax.swing.JLabel();
        txtAltura = new javax.swing.JLabel();
        txtIdade = new javax.swing.JLabel();
        txtNivelDeAtividade = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnLimpar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        respostaGastoBasal = new javax.swing.JTextField();
        respostaGastoTotal = new javax.swing.JTextField();
        btnVoltarGastoCalorico = new javax.swing.JButton();
        btnSairGastoCalorico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(470, 450));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCalcularGasto.setText("Calcular");
        btnCalcularGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularGastoActionPerformed(evt);
            }
        });

        grupoRadio.add(radioMulherTelaGasto);
        radioMulherTelaGasto.setText("Mulher");
        radioMulherTelaGasto.setToolTipText("Para selecionar Mulher");
        radioMulherTelaGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMulherTelaGastoActionPerformed(evt);
            }
        });

        grupoRadio.add(radioHomemTelaGasto);
        radioHomemTelaGasto.setText("Homem");
        radioHomemTelaGasto.setToolTipText("Para selecionar homem");
        radioHomemTelaGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioHomemTelaGastoActionPerformed(evt);
            }
        });

        campoPesoTelaGasto.setToolTipText("Insira a altura");
        campoPesoTelaGasto.setNextFocusableComponent(campoAlturaTelaGasto);

        campoAlturaTelaGasto.setToolTipText("Insira a altura");
        campoAlturaTelaGasto.setNextFocusableComponent(campoIdadeTelaGasto);

        campoIdadeTelaGasto.setToolTipText("Insira a idade");
        campoIdadeTelaGasto.setNextFocusableComponent(btnCalcularGasto);

        txtPeso.setText("Peso (kg):");

        txtAltura.setText("Altura (cm):");

        txtIdade.setText("Idade:");

        txtNivelDeAtividade.setText("Nível de Atividade:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedentário", "Leve (1 a 3 dias/semana)", "Moderado (3 a 5 dias/semana)", "Ativo (5 a 6 dias/semana)", "Extremamente ativo (diário)", " ", " " }));
        jComboBox1.setToolTipText("Selecione o nível de atividade em que você está!");

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(radioMulherTelaGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addComponent(radioHomemTelaGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnCalcularGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNivelDeAtividade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, 0, 358, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPeso)
                            .addComponent(txtAltura)
                            .addComponent(txtIdade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(campoPesoTelaGasto, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                            .addComponent(campoAlturaTelaGasto)
                            .addComponent(campoIdadeTelaGasto))))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioMulherTelaGasto)
                    .addComponent(radioHomemTelaGasto))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoPesoTelaGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPeso))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoAlturaTelaGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAltura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoIdadeTelaGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdade))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNivelDeAtividade)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcularGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Gasto Basal:");

        jLabel2.setText("Gasto Total:");

        respostaGastoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respostaGastoTotalActionPerformed(evt);
            }
        });

        btnVoltarGastoCalorico.setText("Voltar");
        btnVoltarGastoCalorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarGastoCaloricoActionPerformed(evt);
            }
        });

        btnSairGastoCalorico.setText("Sair");
        btnSairGastoCalorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairGastoCaloricoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(respostaGastoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(respostaGastoBasal)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(btnVoltarGastoCalorico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSairGastoCalorico)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(respostaGastoBasal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(respostaGastoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltarGastoCalorico)
                    .addComponent(btnSairGastoCalorico))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularGastoActionPerformed

        try {

            double calBasal = 0;
            double altura = Double.parseDouble(campoAlturaTelaGasto.getText().replace(",", "."));
            double peso = Double.parseDouble(campoPesoTelaGasto.getText().replace(",", "."));
            double idade = Double.parseDouble(campoIdadeTelaGasto.getText().replace(",", "."));
            String txtGastoBasal = "";
            String txtGastoTotal = "";
            String valorSelecionado = (String) jComboBox1.getSelectedItem();

            if (!radioHomemTelaGasto.
                    isSelected() && !radioMulherTelaGasto.
                            isSelected() && !campoPesoTelaGasto.
                            getText().
                            isEmpty() && campoAlturaTelaGasto.
                            getText().isEmpty() && campoIdadeTelaGasto.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Selecione Homem ou Mulher e preencha todos os campos");
            } else {
                if (radioMulherTelaGasto.isSelected()) {
                    calBasal = 66 + (13.8 * peso) + (5 * altura) - (6.8 * idade);
                    txtGastoBasal = Double.toString(calBasal);
                   
                    txtGastoBasal = String.format("%.2f", calBasal);
                }
                if (radioHomemTelaGasto.isSelected()) {
                    calBasal = 655 + (9.6 * peso) + (1.9 * altura) - (4.7 * idade);
                    txtGastoBasal = Double.toString(calBasal);
                }

                if (valorSelecionado != null && valorSelecionado.equalsIgnoreCase("Sedentário")) {
                    double calTotal = calBasal * 1.2;
                    txtGastoTotal = Double.toString(calTotal);
                    txtGastoTotal = String.format("%.2f", calTotal);
                    txtGastoBasal = String.format("%.2f", calBasal);

                } else if (valorSelecionado != null && valorSelecionado.equalsIgnoreCase("Leve (1 a 3 dias/semana)")) {
                    double calTotal = calBasal * 1.375;
                    txtGastoTotal = Double.toString(calTotal);

                } else if (valorSelecionado != null && valorSelecionado.equalsIgnoreCase("Moderado (3 a 5 dias/semana)")) {
                    double calTotal = calBasal * 1.55;
                    txtGastoTotal = Double.toString(calTotal);
                    txtGastoTotal = String.format("%.2f", calTotal);
                    txtGastoBasal = String.format("%.2f", calBasal);
                } else if (valorSelecionado != null && valorSelecionado.equalsIgnoreCase("Ativo (5 a 6 dias/semana)")) {
                    double calTotal = calBasal * 1.725;
                    txtGastoTotal = Double.toString(calTotal);
                    txtGastoTotal = String.format("%.2f", calTotal);
                    txtGastoBasal = String.format("%.2f", calBasal);

                } else if (valorSelecionado != null && valorSelecionado.equalsIgnoreCase("Extremamente ativo (diário)")) {
                    double calTotal = calBasal * 1.9;
                    txtGastoTotal = Double.toString(calTotal);
                   txtGastoTotal = String.format("%.2f", calTotal);
                    txtGastoBasal = String.format("%.2f", calBasal);

                }
                
                
               


                respostaGastoTotal.setText(txtGastoTotal);
                respostaGastoBasal.setText(txtGastoBasal);
            }
        } catch (NumberFormatException error) {
            JOptionPane.showMessageDialog(null, error.getMessage() + " Preencha todos os campo, e somente são aceitos números!\n");
        }

    }//GEN-LAST:event_btnCalcularGastoActionPerformed

    private void radioMulherTelaGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMulherTelaGastoActionPerformed

    }//GEN-LAST:event_radioMulherTelaGastoActionPerformed

    private void respostaGastoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respostaGastoTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_respostaGastoTotalActionPerformed

    private void radioHomemTelaGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioHomemTelaGastoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioHomemTelaGastoActionPerformed

    private void btnVoltarGastoCaloricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarGastoCaloricoActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarGastoCaloricoActionPerformed

    private void btnSairGastoCaloricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairGastoCaloricoActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairGastoCaloricoActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btnLimparActionPerformed
    
      public void limpar() {
       respostaGastoTotal.setText("");
        respostaGastoBasal.setText("");
        campoAlturaTelaGasto.setText("");
        campoIdadeTelaGasto.setText("");
        campoPesoTelaGasto.setText("");
       grupoRadio.clearSelection();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularGasto;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSairGastoCalorico;
    private javax.swing.JButton btnVoltarGastoCalorico;
    private javax.swing.JTextField campoAlturaTelaGasto;
    private javax.swing.JTextField campoIdadeTelaGasto;
    private javax.swing.JTextField campoPesoTelaGasto;
    private javax.swing.ButtonGroup grupoRadio;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton radioHomemTelaGasto;
    private javax.swing.JRadioButton radioMulherTelaGasto;
    private javax.swing.JTextField respostaGastoBasal;
    private javax.swing.JTextField respostaGastoTotal;
    private javax.swing.JLabel txtAltura;
    private javax.swing.JLabel txtIdade;
    private javax.swing.JLabel txtNivelDeAtividade;
    private javax.swing.JLabel txtPeso;
    // End of variables declaration//GEN-END:variables
}
